name: Build & Deploy PNPMD site

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '.scripts/**'
      - 'pnpmd.map'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python (inside container)
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
          ln -sf /usr/bin/python3 /usr/local/bin/python

      - name: Install pandoc-crossref
        run: |
          VER=0.3.17.0
          wget -q https://github.com/lierdakil/pandoc-crossref/releases/download/v$VER/pandoc-crossref-Linux.tar.xz
          tar -xJf pandoc-crossref-Linux.tar.xz
          install -m0755 pandoc-crossref /usr/local/bin/pandoc-crossref
          pandoc-crossref --version

      - name: Build site (no commits)
        env:
          # Optional override: set repo Variable BASE_URL to a custom domain
          BASE_URL: ${{ vars.BASE_URL || format('https://{0}.github.io/{1}', github.repository_owner, github.event.repository.name) }}
        run: |
          python .scripts/build_site.py
          mkdir -p site && touch site/.nojekyll

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
